name: Build and Create Executable

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C compiler
      run: sudo apt-get install -y build-essential

    - name: Compile test.c
      run: gcc -o test_executable test.c

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: test_executable
        path: test_executable
