name: Build C Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get install gcc

      - name: Build the executable
        run: gcc hello.c -o hello.exe

      - name: Upload the executable
        uses: actions/upload-artifact@v3
        with:
          name: hello-exe
          path: hello.exe
