name: Build and Create Executable on Windows

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat" || echo "No suitable vcvars64.bat found"

    - name: Compile test.c
      shell: cmd
      run: cl /EHsc test.c /Fe:test_executable.exe

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: test_executable
        path: test_executable.exe
