name: Build and Create Executable windows using pyinstaller

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create executable
      run: |
        pyinstaller --onefile --windowed hello.py

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: hello_executable
        path: dist/hello.exe
